---
name: sysbench

releases:
- name: sysbench
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: sysbench_oltp
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: sysbench_oltp
    consumes:
      db: {from: db, deployment: tidb}
    properties:
      test_to_run: tests.example
  vm_type: default
  stemcell: default
  networks:
  - name: default
